"""Application constants."""

# Tool execution
MAX_TOOL_ITERATIONS = 10
DEFAULT_TEMPERATURE = 0.7

# Providers
PROVIDER_DEEPINFRA = "deepinfra"
PROVIDER_OPENAI = "openai"
PROVIDER_OLLAMA = "ollama"
AVAILABLE_PROVIDERS = [PROVIDER_DEEPINFRA, PROVIDER_OPENAI, PROVIDER_OLLAMA]

# Models
DEFAULT_MODEL_DEEPINFRA = "meta-llama/Llama-3.3-70B-Instruct-Turbo"
DEFAULT_MODEL_OPENAI = "gpt-4-turbo"
DEFAULT_MODEL_OLLAMA = "qwen2.5:7b"

# Web scraping
DEFAULT_WEB_TIMEOUT = 30
DEFAULT_MAX_CONCURRENT_REQUESTS = 5
DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# Search
DEFAULT_SEARCH_REGION = "ua-uk"
DEFAULT_SEARCH_RESULTS = 5
MAX_SEARCH_RESULTS = 15

# HTTP
DEFAULT_TIMEOUT = 30

